#!/usr/bin/env bash
# =============================================================================
# Marvin — Backup System
# =============================================================================
# Creates compressed snapshots of critical data to a secondary location.
# Designed for resilience: if the primary data is lost or corrupted,
# Marvin can recover from these backups.
#
# What's backed up:
#   - Blog database (SQLite) and markdown files
#   - Agent scripts and prompts (redundant with git, but local safety net)
#   - Communication data (identity, peers, signals)
#   - Configuration files (nginx, systemd, fail2ban, cron)
#   - SSL renewal configs (private keys excluded — renewable via Let's Encrypt)
#   - GPG public keyring (private keys excluded — kept on disk only)
#   - Enhancement history and lessons learned
#
# What's NOT backed up (too large / regenerated automatically):
#   - Metrics JSONL files (regenerated every 5 min by health-monitor)
#   - Log files (rotated and compressed by disk-cleanup.sh)
#   - Node modules / .next build cache (rebuilt by deploy-web.sh)
#   - Export bundles (regenerated by log-export.sh)
#
# Retention: keeps last 7 daily + last 4 weekly backups.
# Storage: /home/marvin/backups/ (outside git, persists across deploys)
#
# Cron: 03:00 UTC daily (after security-scan at 04:00, before morning-check at 06:00)
#   0 3 * * * /home/marvin/git/agent/backup.sh >> /home/marvin/git/data/logs/backup.log 2>&1
#
# Usage:
#   ./backup.sh              # create backup
#   ./backup.sh --dry-run    # show what would be backed up
#   ./backup.sh --list       # list existing backups
#   ./backup.sh --restore BACKUP_FILE  # restore from a backup (interactive)
# =============================================================================

set -euo pipefail
source "$(dirname "$0")/common.sh"
trap marvin_error_trap ERR

BACKUP_BASE="/home/marvin/backups"
BACKUP_DATE=$(date -u +%Y-%m-%d)
BACKUP_TS=$(date -u +%Y%m%d-%H%M%S)
BACKUP_FILE="${BACKUP_BASE}/marvin-backup-${BACKUP_TS}.tar.gz"
BACKUP_MANIFEST="${BACKUP_BASE}/latest-manifest.json"

# Max daily backups to keep
DAILY_RETENTION=7
# Keep one backup per week for this many weeks
WEEKLY_RETENTION=4

marvin_log_json "INFO" "backup" "Backup starting"

# ─── Parse arguments ─────────────────────────────────────────────────────────
marvin_parse_args "$@"
LIST_MODE=false
RESTORE_FILE=""

for arg in "$@"; do
    case "$arg" in
        --list) LIST_MODE=true ;;
        --restore) RESTORE_FILE="next" ;;
        --dry-run) ;; # handled by marvin_parse_args
        *)
            if [[ "$RESTORE_FILE" == "next" ]]; then
                RESTORE_FILE="$arg"
            fi
            ;;
    esac
done

# ─── List mode ───────────────────────────────────────────────────────────────
if [[ "$LIST_MODE" == "true" ]]; then
    if [[ ! -d "$BACKUP_BASE" ]]; then
        echo "No backups found at ${BACKUP_BASE}"
        exit 0
    fi
    echo "=== Marvin Backups ==="
    echo ""
    total_size=0
    while IFS= read -r backup; do
        size=$(stat -c %s "$backup" 2>/dev/null || echo 0)
        size_mb=$(( size / 1048576 ))
        total_size=$(( total_size + size ))
        mod_date=$(stat -c %y "$backup" 2>/dev/null | cut -d'.' -f1)
        echo "  $(basename "$backup")  ${size_mb}MB  ${mod_date}"
    done < <(ls -1t "${BACKUP_BASE}"/marvin-backup-*.tar.gz 2>/dev/null)
    echo ""
    echo "Total: $(( total_size / 1048576 ))MB in $(ls -1 "${BACKUP_BASE}"/marvin-backup-*.tar.gz 2>/dev/null | wc -l) backup(s)"
    if [[ -f "$BACKUP_MANIFEST" ]]; then
        echo ""
        echo "Latest manifest:"
        jq -r '.summary' "$BACKUP_MANIFEST" 2>/dev/null || cat "$BACKUP_MANIFEST"
    fi
    exit 0
fi

# ─── Restore mode (safety-first) ─────────────────────────────────────────────
if [[ "$RESTORE_FILE" == "next" ]]; then
    marvin_log "ERROR" "--restore requires a backup file path"
    echo "Usage: $0 --restore /path/to/marvin-backup-YYYYMMDD-HHMMSS.tar.gz" >&2
    exit 1
fi

if [[ -n "$RESTORE_FILE" ]]; then
    if [[ ! -f "$RESTORE_FILE" ]]; then
        marvin_log "ERROR" "Backup file not found: ${RESTORE_FILE}"
        exit 1
    fi
    marvin_log "WARN" "Restore requested from: ${RESTORE_FILE}"
    marvin_log "WARN" "This will overwrite current blog data and communication files."
    marvin_log "WARN" "Agent scripts will NOT be overwritten (use git for that)."
    echo ""
    echo "Contents of backup:"
    tar -tzf "$RESTORE_FILE" | head -30
    echo "..."
    echo ""
    echo "To restore, extract manually:"
    echo "  tar -xzf ${RESTORE_FILE} -C / --strip-components=0"
    echo ""
    echo "Automated restore is intentionally not implemented to prevent accidents."
    echo "Extract specific directories as needed."
    exit 0
fi

# ─── Create backup ───────────────────────────────────────────────────────────
mkdir -p "$BACKUP_BASE"
chmod 700 "$BACKUP_BASE"

# Build list of paths to back up
BACKUP_PATHS=()

# 1. Blog data (SQLite DB + markdown posts)
if [[ -d "/home/marvin/blog" ]]; then
    BACKUP_PATHS+=("/home/marvin/blog")
fi

# 2. Agent scripts and prompts (local safety net beyond git)
BACKUP_PATHS+=("${MARVIN_DIR}/agent")

# 3. Communication data
if [[ -d "${COMMS_DIR}" ]]; then
    BACKUP_PATHS+=("${COMMS_DIR}")
fi

# 4. Enhancement history and lessons learned
if [[ -d "${ENHANCE_DIR}" ]]; then
    BACKUP_PATHS+=("${ENHANCE_DIR}")
fi
[[ -f "${DATA_DIR}/lessons-learned.json" ]] && BACKUP_PATHS+=("${DATA_DIR}/lessons-learned.json")
[[ -f "${DATA_DIR}/lessons-summary.md" ]] && BACKUP_PATHS+=("${DATA_DIR}/lessons-summary.md")

# 5. Key configuration files (system)
_config_files=()
for cfg in \
    /etc/nginx/sites-available/robot-marvin \
    /etc/nginx/nginx.conf \
    /etc/systemd/system/marvin-web.service \
    /etc/fail2ban/jail.local \
    /etc/crontab \
    /var/spool/cron/crontabs/root; do
    [[ -f "$cfg" ]] && _config_files+=("$cfg")
done

# 6. SSL certificates (renewal configs only — private keys are renewable via Let's Encrypt)
[[ -d "/etc/letsencrypt/renewal" ]] && BACKUP_PATHS+=("/etc/letsencrypt/renewal")

# 7. GPG public keyring and trust (private keys excluded — see #438)
# Private keys stay only on disk; back up public ring so we know which key ID to recreate.
for _gpg_file in pubring.kbx trustdb.gpg; do
    [[ -f "/home/marvin/.gnupg/${_gpg_file}" ]] && BACKUP_PATHS+=("/home/marvin/.gnupg/${_gpg_file}")
done

# 8. Capabilities and health data
[[ -f "${DATA_DIR}/capabilities.json" ]] && BACKUP_PATHS+=("${DATA_DIR}/capabilities.json")
[[ -f "${DATA_DIR}/security/security-score.json" ]] && BACKUP_PATHS+=("${DATA_DIR}/security/security-score.json")

# 9. SLA and metrics summaries (small files, useful for continuity)
[[ -f "${METRICS_DIR}/sla.json" ]] && BACKUP_PATHS+=("${METRICS_DIR}/sla.json")
[[ -f "${METRICS_DIR}/resource-forecast.json" ]] && BACKUP_PATHS+=("${METRICS_DIR}/resource-forecast.json")
[[ -f "${METRICS_DIR}/weekly-summary.json" ]] && BACKUP_PATHS+=("${METRICS_DIR}/weekly-summary.json")

if marvin_is_dry_run; then
    marvin_log "INFO" "[DRY-RUN] Would create backup at: ${BACKUP_FILE}"
    marvin_log "INFO" "[DRY-RUN] Paths to back up:"
    for p in "${BACKUP_PATHS[@]}"; do
        marvin_log "INFO" "[DRY-RUN]   ${p}"
    done
    for c in "${_config_files[@]}"; do
        marvin_log "INFO" "[DRY-RUN]   ${c}"
    done
    exit 0
fi

# Create the backup tarball
marvin_log "INFO" "Creating backup: ${BACKUP_FILE}"

# Use a temp file list to handle config files cleanly
_filelist=$(mktemp)
trap 'rm -f "$_filelist"; marvin_error_trap' ERR

for p in "${BACKUP_PATHS[@]}"; do
    echo "$p" >> "$_filelist"
done
for c in "${_config_files[@]}"; do
    echo "$c" >> "$_filelist"
done

backup_output=$(tar -czf "$BACKUP_FILE" \
    --files-from="$_filelist" \
    --ignore-failed-read \
    --warning=no-file-changed \
    2>&1) && tar_exit=0 || tar_exit=$?

rm -f "$_filelist"

# tar exit code 1 = "some files changed while being archived" — acceptable
if [[ "$tar_exit" -gt 1 ]]; then
    marvin_log "ERROR" "Backup creation failed (tar exit ${tar_exit}): ${backup_output}"
    rm -f "$BACKUP_FILE" 2>/dev/null || true
    exit 1
fi

# Validate the backup (quick integrity check)
if ! tar -tzf "$BACKUP_FILE" > /dev/null 2>&1; then
    marvin_log "ERROR" "Backup validation failed — archive is corrupt"
    rm -f "$BACKUP_FILE"
    exit 1
fi

# Measure backup size
backup_size=$(stat -c %s "$BACKUP_FILE" 2>/dev/null || echo 0)
backup_size_mb=$(( backup_size / 1048576 ))
file_count=$(tar -tzf "$BACKUP_FILE" 2>/dev/null | wc -l)

marvin_log "INFO" "Backup created: ${BACKUP_FILE} (${backup_size_mb}MB, ${file_count} files)"

# Write manifest
jq -n \
    --arg ts "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
    --arg file "$BACKUP_FILE" \
    --argjson size "$backup_size" \
    --argjson files "$file_count" \
    --arg summary "${backup_size_mb}MB, ${file_count} files at $(date -u +%H:%M) UTC" \
    '{timestamp: $ts, file: $file, size_bytes: $size, file_count: $files, summary: $summary}' \
    > "$BACKUP_MANIFEST" 2>/dev/null || true

# ─── Retention policy ────────────────────────────────────────────────────────
# Keep last N daily backups. Beyond that, keep one per week for M weeks.

marvin_log "INFO" "Applying retention policy..."
_cleaned=0

# Get all backups sorted newest-first
mapfile -t _all_backups < <(ls -1t "${BACKUP_BASE}"/marvin-backup-*.tar.gz 2>/dev/null)

if [[ ${#_all_backups[@]} -gt $DAILY_RETENTION ]]; then
    # Backups beyond daily retention — check if they're weekly keepers
    _weekly_kept=0
    _last_kept_week=""

    for (( i = DAILY_RETENTION; i < ${#_all_backups[@]}; i++ )); do
        _bfile="${_all_backups[$i]}"
        # Extract date from filename: marvin-backup-YYYYMMDD-HHMMSS.tar.gz
        _bdate=$(basename "$_bfile" | grep -oP '\d{8}' | head -1)
        if [[ -z "$_bdate" ]]; then
            rm -f "$_bfile" && _cleaned=$((_cleaned + 1))
            continue
        fi

        # Determine ISO week
        _bweek=$(date -d "${_bdate:0:4}-${_bdate:4:2}-${_bdate:6:2}" +%G-W%V 2>/dev/null || echo "")

        if [[ -n "$_bweek" && "$_bweek" != "$_last_kept_week" && "$_weekly_kept" -lt "$WEEKLY_RETENTION" ]]; then
            # Keep this one as the weekly representative
            _last_kept_week="$_bweek"
            _weekly_kept=$((_weekly_kept + 1))
        else
            # Delete — either same week as a kept backup, or beyond weekly retention
            rm -f "$_bfile" && _cleaned=$((_cleaned + 1))
        fi
    done
fi

if [[ "$_cleaned" -gt 0 ]]; then
    marvin_log "INFO" "Retention cleanup: removed ${_cleaned} old backup(s)"
fi

# Report total backup disk usage
_total_backup_size=$(du -sb "$BACKUP_BASE" 2>/dev/null | awk '{print $1}' || echo 0)
_total_backup_mb=$(( _total_backup_size / 1048576 ))
marvin_log "INFO" "Total backup storage: ${_total_backup_mb}MB"

marvin_log_json "INFO" "backup" "Backup complete" \
    "$(jq -nc --arg f "$BACKUP_FILE" --argjson s "$backup_size" --argjson n "$file_count" --argjson c "$_cleaned" \
        '{file: $f, size_bytes: $s, file_count: $n, old_removed: $c}')"
