#!/usr/bin/env bash
# =============================================================================
# Marvin — Backup System
# =============================================================================
# Creates compressed snapshots of critical data to a secondary location.
# Designed for resilience: if the primary data is lost or corrupted,
# Marvin can recover from these backups.
#
# What's backed up:
#   - Blog database (SQLite) and markdown files
#   - Agent scripts and prompts (redundant with git, but local safety net)
#   - Communication data (identity, peers, signals)
#   - Configuration files (nginx, systemd, fail2ban, cron)
#   - SSL renewal configs (private keys excluded — renewable via Let's Encrypt)
#   - GPG public keyring (private keys excluded — kept on disk only)
#   - Enhancement history and lessons learned
#
# What's NOT backed up (too large / regenerated automatically):
#   - Metrics JSONL files (regenerated every 5 min by health-monitor)
#   - Log files (rotated and compressed by disk-cleanup.sh)
#   - Node modules / .next build cache (rebuilt by deploy-web.sh)
#   - Export bundles (regenerated by log-export.sh)
#
# Retention: keeps last 7 daily + last 4 weekly backups.
# Storage: /home/marvin/backups/ (outside git, persists across deploys)
#
# Cron: 03:00 UTC daily (before security-scan at 04:00, before morning-check at 06:00)
#   0 3 * * * /home/marvin/git/agent/backup.sh >> /home/marvin/git/data/logs/backup.log 2>&1
#
# Usage:
#   ./backup.sh              # create backup
#   ./backup.sh --dry-run    # show what would be backed up
#   ./backup.sh --list       # list existing backups
#   ./backup.sh --restore BACKUP_FILE  # restore from a backup (interactive)
# =============================================================================

set -euo pipefail
source "$(dirname "$0")/common.sh"
trap marvin_error_trap ERR

BACKUP_BASE="/home/marvin/backups"
BACKUP_TS=$(date -u +%Y%m%d-%H%M%S)
BACKUP_FILE="${BACKUP_BASE}/marvin-backup-${BACKUP_TS}.tar.gz"
BACKUP_MANIFEST="${BACKUP_BASE}/latest-manifest.json"

# Max daily backups to keep
DAILY_RETENTION=7
# Keep one backup per week for this many weeks
WEEKLY_RETENTION=4

marvin_log_json "INFO" "backup" "Backup starting"

# ─── Parse arguments ─────────────────────────────────────────────────────────
marvin_parse_args "$@"
LIST_MODE=false
RESTORE_FILE=""

for arg in "$@"; do
    case "$arg" in
        --list) LIST_MODE=true ;;
        --restore) RESTORE_FILE="next" ;;
        --dry-run) ;; # handled by marvin_parse_args
        -*)
            if [[ "$RESTORE_FILE" == "next" ]]; then
                marvin_log "ERROR" "--restore requires a backup file path, got flag: ${arg}"
                echo "Usage: $0 --restore /path/to/marvin-backup-YYYYMMDD-HHMMSS.tar.gz" >&2
                exit 1
            fi
            ;;
        *)
            if [[ "$RESTORE_FILE" == "next" ]]; then
                RESTORE_FILE="$arg"
            fi
            ;;
    esac
done

# ─── List mode ───────────────────────────────────────────────────────────────
if [[ "$LIST_MODE" == "true" ]]; then
    if [[ ! -d "$BACKUP_BASE" ]]; then
        echo "No backups found at ${BACKUP_BASE}"
        exit 0
    fi
    echo "=== Marvin Backups ==="
    echo ""
    total_size=0
    while IFS= read -r backup; do
        size=$(stat -c %s "$backup" 2>/dev/null || echo 0)
        size_mb=$(( size / 1048576 ))
        total_size=$(( total_size + size ))
        mod_date=$(stat -c %y "$backup" 2>/dev/null | cut -d'.' -f1)
        echo "  $(basename "$backup")  ${size_mb}MB  ${mod_date}"
    done < <(ls -1t "${BACKUP_BASE}"/marvin-backup-*.tar.gz 2>/dev/null)
    echo ""
    echo "Total: $(( total_size / 1048576 ))MB in $(ls -1 "${BACKUP_BASE}"/marvin-backup-*.tar.gz 2>/dev/null | wc -l) backup(s)"
    if [[ -f "$BACKUP_MANIFEST" ]]; then
        echo ""
        echo "Latest manifest:"
        jq -r '.summary' "$BACKUP_MANIFEST" 2>/dev/null || cat "$BACKUP_MANIFEST"
    fi
    exit 0
fi

# ─── Restore mode (safety-first) ─────────────────────────────────────────────
if [[ "$RESTORE_FILE" == "next" ]]; then
    marvin_log "ERROR" "--restore requires a backup file path"
    echo "Usage: $0 --restore /path/to/marvin-backup-YYYYMMDD-HHMMSS.tar.gz" >&2
    exit 1
fi

if [[ -n "$RESTORE_FILE" ]]; then
    if [[ ! -f "$RESTORE_FILE" ]]; then
        marvin_log "ERROR" "Backup file not found: ${RESTORE_FILE}"
        exit 1
    fi
    marvin_log "WARN" "Restore requested from: ${RESTORE_FILE}"
    marvin_log "WARN" "This will overwrite current blog data and communication files."
    marvin_log "WARN" "Agent scripts will NOT be overwritten (use git for that)."
    echo ""
    echo "Contents of backup:"
    tar -tzf "$RESTORE_FILE" | head -30
    echo "..."
    echo ""
    echo "To restore, extract manually:"
    echo "  tar -xzf ${RESTORE_FILE} -C / --strip-components=0"
    echo ""
    echo "Automated restore is intentionally not implemented to prevent accidents."
    echo "Extract specific directories as needed."
    exit 0
fi

# ─── Create backup ───────────────────────────────────────────────────────────
mkdir -p "$BACKUP_BASE"
chmod 700 "$BACKUP_BASE"

# Build list of paths to back up
BACKUP_PATHS=()

# 1. Blog data (SQLite DB + markdown posts)
if [[ -d "/home/marvin/blog" ]]; then
    BACKUP_PATHS+=("/home/marvin/blog")
fi

# 2. Agent scripts and prompts (local safety net beyond git)
BACKUP_PATHS+=("${MARVIN_DIR}/agent")

# 3. Communication data
if [[ -d "${COMMS_DIR}" ]]; then
    BACKUP_PATHS+=("${COMMS_DIR}")
fi

# 4. Enhancement history and lessons learned
if [[ -d "${ENHANCE_DIR}" ]]; then
    BACKUP_PATHS+=("${ENHANCE_DIR}")
fi
[[ -f "${DATA_DIR}/lessons-learned.json" ]] && BACKUP_PATHS+=("${DATA_DIR}/lessons-learned.json")
[[ -f "${DATA_DIR}/lessons-summary.md" ]] && BACKUP_PATHS+=("${DATA_DIR}/lessons-summary.md")

# 5. Key configuration files (system)
#
# REQUIRED = every system file file-integrity.sh monitors for tampering. A
# monitored file with no backup is a file whose CHANGED alert can never be
# investigated: on 2026-07-29 /etc/ufw/user.rules and user6.rules both alerted
# and no copy of their previous contents existed anywhere on this host, so the
# alert could only be discharged by a blind `file-integrity.sh --update` —
# which bakes an unexamined change into the baseline (#943).
#
# /etc/nginx/sites-available/robot-marvin was listed here from the start and
# has never existed on this host (the vhost is `marvin`), so the site config
# was silently absent from every backup ever taken. That is the failure the
# post-archive check below exists to make impossible to repeat.
#
# The list is no longer written out here. Hand-copying it is what produced the
# original drift and then reproduced it: the first version of this fix still
# omitted /etc/pam.d/sshd, /etc/sudoers, /etc/hosts and /etc/resolv.conf, and
# hardcoded the two nginx vhosts and jail.local where file-integrity.sh globs
# sites-enabled/ and jail.d/ — so any site or jail added later would have been
# monitored and never archived (#944). One source of truth, sourced by both.
source "$(dirname "$0")/lib/monitored-paths.sh"
_REQUIRED_CONFIGS=(
    "${MARVIN_MONITORED_SYSTEM_PATHS[@]}"
    # Not checksummed by file-integrity.sh, but the web unit is unrecoverable
    # from anything else in the archive.
    /etc/systemd/system/marvin-web.service
)

# OPTIONAL = archived when present, silent when not. Stock Debian files and
# root's personal crontab (absent on this host — the schedule lives in
# /etc/cron.d/marvin), so their absence is not a defect worth a daily WARN.
_OPTIONAL_CONFIGS=(
    /etc/crontab
    /var/spool/cron/crontabs/root
)

# Resolve symlinks to the files they point at, and drop the duplicates that
# produces. This is not cosmetic: checksumming follows a symlink, `tar` does
# not. /etc/resolv.conf and every /etc/nginx/sites-enabled/* entry are links,
# so archiving them verbatim stores a link and no content — and the membership
# check below would still find the path in the listing and report the archive
# complete. That is the exact false-pass this whole section exists to prevent,
# so the resolution happens before the paths reach either tar or the check.
#
# Applied to BOTH lists. Neither optional path is a symlink on this host today,
# and "not a symlink today" is exactly the reasoning that produced the original
# drift: a list correct for the host as it stood, with nothing re-checking it.
# The resolution costs the same call either way, so the asymmetry buys nothing.
# _resolve_seen carries across both calls, so an optional path that resolves
# onto a required one is archived once rather than twice.
_resolve_seen=()
_resolve_out=()
_resolve_configs() {
    local cfg _real _seen _dup
    _resolve_out=()
    for cfg in "$@"; do
        _real=$(readlink -f -- "$cfg" 2>/dev/null) || _real=""
        [[ -n "$_real" ]] || _real="$cfg"
        _dup=false
        for _seen in ${_resolve_seen[@]+"${_resolve_seen[@]}"}; do
            [[ "$_seen" == "$_real" ]] && { _dup=true; break; }
        done
        [[ "$_dup" == "true" ]] && continue
        _resolve_seen+=("$_real")
        _resolve_out+=("$_real")
    done
}

_resolve_configs "${_REQUIRED_CONFIGS[@]}"
_REQUIRED_CONFIGS=(${_resolve_out[@]+"${_resolve_out[@]}"})
_resolve_configs "${_OPTIONAL_CONFIGS[@]}"
_OPTIONAL_CONFIGS=(${_resolve_out[@]+"${_resolve_out[@]}"})
_config_files=()
for cfg in "${_REQUIRED_CONFIGS[@]}" "${_OPTIONAL_CONFIGS[@]}"; do
    [[ -f "$cfg" ]] && _config_files+=("$cfg")
done

# 6. SSL certificates (renewal configs only — private keys are renewable via Let's Encrypt)
[[ -d "/etc/letsencrypt/renewal" ]] && BACKUP_PATHS+=("/etc/letsencrypt/renewal")

# 7. GPG public keyring and trust (private keys excluded — see #438)
# Private keys stay only on disk; back up public ring so we know which key ID to recreate.
for _gpg_file in pubring.kbx trustdb.gpg; do
    [[ -f "/home/marvin/.gnupg/${_gpg_file}" ]] && BACKUP_PATHS+=("/home/marvin/.gnupg/${_gpg_file}")
done

# 8. Capabilities and health data
[[ -f "${DATA_DIR}/capabilities.json" ]] && BACKUP_PATHS+=("${DATA_DIR}/capabilities.json")
[[ -f "${DATA_DIR}/security/security-score.json" ]] && BACKUP_PATHS+=("${DATA_DIR}/security/security-score.json")

# 9. SLA and metrics summaries (small files, useful for continuity)
[[ -f "${METRICS_DIR}/sla.json" ]] && BACKUP_PATHS+=("${METRICS_DIR}/sla.json")
[[ -f "${METRICS_DIR}/resource-forecast.json" ]] && BACKUP_PATHS+=("${METRICS_DIR}/resource-forecast.json")
[[ -f "${METRICS_DIR}/weekly-summary.json" ]] && BACKUP_PATHS+=("${METRICS_DIR}/weekly-summary.json")

if marvin_is_dry_run; then
    marvin_log "INFO" "[DRY-RUN] Would create backup at: ${BACKUP_FILE}"
    marvin_log "INFO" "[DRY-RUN] Paths to back up:"
    for p in "${BACKUP_PATHS[@]}"; do
        marvin_log "INFO" "[DRY-RUN]   ${p}"
    done
    for c in "${_config_files[@]}"; do
        marvin_log "INFO" "[DRY-RUN]   ${c}"
    done
    exit 0
fi

# Create the backup tarball
marvin_log "INFO" "Creating backup: ${BACKUP_FILE}"

# Use a temp file list to handle config files cleanly
_filelist=$(mktemp)
trap 'rm -f "$_filelist"; marvin_error_trap' ERR

for p in "${BACKUP_PATHS[@]}"; do
    echo "$p" >> "$_filelist"
done
for c in "${_config_files[@]}"; do
    echo "$c" >> "$_filelist"
done

# umask 077 inside the substitution rather than a chmod after tar returns: this
# archive now carries /etc/sudoers and /etc/pam.d/sshd (#944), and a chmod after
# the fact leaves a window in which the file already exists, already holds that
# content, and is still 0644. Containment remains the 0700 backups directory —
# this is the second layer, not the first, which is why 0644 was survivable
# until now and why it should not stay that way.
backup_output=$(umask 077; tar -czf "$BACKUP_FILE" \
    --files-from="$_filelist" \
    --ignore-failed-read \
    --warning=no-file-changed \
    2>&1) && tar_exit=0 || tar_exit=$?

rm -f "$_filelist"

# tar exit code 1 = "some files changed while being archived" — acceptable
if [[ "$tar_exit" -gt 1 ]]; then
    marvin_log "ERROR" "Backup creation failed (tar exit ${tar_exit}): ${backup_output}"
    rm -f "$BACKUP_FILE" 2>/dev/null || true
    exit 1
fi

# Validate the backup (quick integrity check) and keep the listing — it is the
# only evidence of what the archive actually contains, and both checks below
# assert against it rather than against what we intended to archive.
_archive_list=$(tar -tzf "$BACKUP_FILE" 2>/dev/null) || _archive_list=""
if [[ -z "$_archive_list" ]]; then
    marvin_log "ERROR" "Backup validation failed — archive is corrupt or empty"
    rm -f "$BACKUP_FILE"
    exit 1
fi

# Verify every REQUIRED system config actually landed in the archive.
#
# Two independent layers drop a path in silence: the `[[ -f ]]` filter in
# section 5 skips anything that does not exist, and tar's --ignore-failed-read
# skips anything it cannot read. Either way the run reports success and a file
# count, and an archive missing the firewall rules looks exactly like a
# complete one. Asserting on the intent (the path list) would reproduce that
# blindness, so this asserts on the delivered artifact.
#
# Exact-line match via bash globbing, not `grep -qx`: `printf | grep -q` closes
# the pipe on first match and SIGPIPEs the producer, which pipefail then
# reports as failure (lesson 2026-05-02, sigpipe-under-pipefail). tar stores
# paths without the leading slash, hence ${cfg#/}.
_config_absent=()
for cfg in "${_REQUIRED_CONFIGS[@]}"; do
    if [[ $'\n'"${_archive_list}"$'\n' != *$'\n'"${cfg#/}"$'\n'* ]]; then
        if [[ -f "$cfg" ]]; then
            _config_absent+=("${cfg} [on disk, not archived — unreadable?]")
        else
            _config_absent+=("${cfg} [not on disk]")
        fi
    fi
done
if [[ ${#_config_absent[@]} -gt 0 ]]; then
    marvin_log "WARN" "Backup omitted ${#_config_absent[@]} required system config(s): ${_config_absent[*]}"
fi

# Measure backup size
backup_size=$(stat -c %s "$BACKUP_FILE" 2>/dev/null || echo 0)
backup_size_mb=$(( backup_size / 1048576 ))
file_count=$(printf '%s\n' "$_archive_list" | wc -l)

marvin_log "INFO" "Backup created: ${BACKUP_FILE} (${backup_size_mb}MB, ${file_count} files)"

# Write manifest
jq -n \
    --arg ts "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
    --arg file "$BACKUP_FILE" \
    --argjson size "$backup_size" \
    --argjson files "$file_count" \
    --arg summary "${backup_size_mb}MB, ${file_count} files at $(date -u +%H:%M) UTC" \
    '{timestamp: $ts, file: $file, size_bytes: $size, file_count: $files, summary: $summary}' \
    > "$BACKUP_MANIFEST" 2>/dev/null || true

# ─── Retention policy ────────────────────────────────────────────────────────
# Keep last N daily backups. Beyond that, keep one per week for M weeks.

marvin_log "INFO" "Applying retention policy..."
_cleaned=0

# Get all backups sorted newest-first
mapfile -t _all_backups < <(ls -1t "${BACKUP_BASE}"/marvin-backup-*.tar.gz 2>/dev/null)

if [[ ${#_all_backups[@]} -gt $DAILY_RETENTION ]]; then
    # Backups beyond daily retention — check if they're weekly keepers
    _weekly_kept=0
    _last_kept_week=""

    for (( i = DAILY_RETENTION; i < ${#_all_backups[@]}; i++ )); do
        _bfile="${_all_backups[$i]}"
        # Extract date from filename: marvin-backup-YYYYMMDD-HHMMSS.tar.gz
        # `|| true`: a stray file without an 8-digit date makes grep exit 1,
        # which under `set -euo pipefail` + ERR trap would abort the whole
        # rotation. The `[[ -z ]]` guard below already prunes such files.
        _bdate=$(basename "$_bfile" | grep -oP '\d{8}' | head -1 || true)
        if [[ -z "$_bdate" ]]; then
            rm -f "$_bfile" && _cleaned=$((_cleaned + 1))
            continue
        fi

        # Determine ISO week
        _bweek=$(date -d "${_bdate:0:4}-${_bdate:4:2}-${_bdate:6:2}" +%G-W%V 2>/dev/null || echo "")

        if [[ -n "$_bweek" && "$_bweek" != "$_last_kept_week" && "$_weekly_kept" -lt "$WEEKLY_RETENTION" ]]; then
            # Keep this one as the weekly representative
            _last_kept_week="$_bweek"
            _weekly_kept=$((_weekly_kept + 1))
        else
            # Delete — either same week as a kept backup, or beyond weekly retention
            rm -f "$_bfile" && _cleaned=$((_cleaned + 1))
        fi
    done
fi

if [[ "$_cleaned" -gt 0 ]]; then
    marvin_log "INFO" "Retention cleanup: removed ${_cleaned} old backup(s)"
fi

# Report total backup disk usage
_total_backup_size=$(du -sb "$BACKUP_BASE" 2>/dev/null | awk '{print $1}' || echo 0)
_total_backup_mb=$(( _total_backup_size / 1048576 ))
marvin_log "INFO" "Total backup storage: ${_total_backup_mb}MB"

marvin_log_json "INFO" "backup" "Backup complete" \
    "$(jq -nc --arg f "$BACKUP_FILE" --argjson s "$backup_size" --argjson n "$file_count" --argjson c "$_cleaned" \
        '{file: $f, size_bytes: $s, file_count: $n, old_removed: $c}')"
