#!/usr/bin/env bash
# =============================================================================
# Marvin — Backup System
# =============================================================================
# Creates compressed snapshots of critical system configs and application data.
# Designed for single-VPS resilience: if configs are lost (bad update, disk
# corruption, accidental deletion), Marvin can restore from local backups.
#
# What gets backed up:
#   1. System configs: nginx, SSH, fail2ban, UFW, cron, postfix, dovecot
#   2. Application data: blog SQLite DB, comms identity, GPG keys (public + private)
#   3. Marvin config: .env, webhook config, export API key
#
# What is NOT backed up (regenerated by cron or stored in git):
#   - data/metrics/ (regenerated every 5 min by health-monitor.sh)
#   - data/logs/ (regenerated daily)
#   - data/exports/ (regenerated daily by log-export.sh)
#   - data/security/ (regenerated daily by security-scan.sh)
#   - web/.next/ (rebuilt by deploy-web.sh)
#   - Agent scripts (in git, pulled by morning-check.sh)
#
# Retention: 7 daily + 4 weekly backups (oldest pruned automatically)
#
# Usage:
#   ./backup.sh                  # full backup
#   ./backup.sh --dry-run        # show what would be backed up
#   ./backup.sh --list           # list existing backups
#   ./backup.sh --restore FILE   # restore from a backup archive
#
# Exit codes:
#   0 = success
#   1 = backup failed
#   2 = restore failed
# =============================================================================

set -euo pipefail
source "$(dirname "$0")/common.sh"
trap marvin_error_trap ERR

BACKUP_BASE="/home/marvin/backups"
DAILY_DIR="${BACKUP_BASE}/daily"
WEEKLY_DIR="${BACKUP_BASE}/weekly"
DAILY_RETENTION=7
WEEKLY_RETENTION=4

marvin_parse_args "$@"

# ─── Parse arguments ─────────────────────────────────────────────────────────
# marvin_parse_args above handles --dry-run; this loop handles backup-specific modes
MODE="backup"
RESTORE_FILE=""
for arg in "$@"; do
    case "$arg" in
        --list) MODE="list" ;;
        --restore) MODE="restore" ;;
        --dry-run) ;; # handled by marvin_parse_args
    esac
done

# Capture --restore FILE argument
if [[ "$MODE" == "restore" ]]; then
    _found_restore=false
    for arg in "$@"; do
        if [[ "$_found_restore" == "true" ]]; then
            RESTORE_FILE="$arg"
            break
        fi
        [[ "$arg" == "--restore" ]] && _found_restore=true
    done
fi

# ─── List mode ───────────────────────────────────────────────────────────────
if [[ "$MODE" == "list" ]]; then
    echo "=== Marvin Backups ==="
    echo ""
    echo "Daily backups (retention: ${DAILY_RETENTION}):"
    if [[ -d "$DAILY_DIR" ]]; then
        ls -lhS "${DAILY_DIR}/"*.tar.gz 2>/dev/null || echo "  (none)"
    else
        echo "  (none)"
    fi
    echo ""
    echo "Weekly backups (retention: ${WEEKLY_RETENTION}):"
    if [[ -d "$WEEKLY_DIR" ]]; then
        ls -lhS "${WEEKLY_DIR}/"*.tar.gz 2>/dev/null || echo "  (none)"
    else
        echo "  (none)"
    fi
    exit 0
fi

# ─── Restore mode ────────────────────────────────────────────────────────────
if [[ "$MODE" == "restore" ]]; then
    if [[ -z "$RESTORE_FILE" || ! -f "$RESTORE_FILE" ]]; then
        marvin_log "ERROR" "Restore file not found: ${RESTORE_FILE:-<not specified>}"
        echo "Usage: backup.sh --restore /path/to/backup.tar.gz"
        exit 2
    fi

    marvin_log "WARN" "Restoring from backup: ${RESTORE_FILE}"

    # Extract to a temp directory first for safety
    restore_tmp=$(mktemp -d)
    if ! tar -xzf "$RESTORE_FILE" -C "$restore_tmp" 2>&1; then
        marvin_log "ERROR" "Failed to extract backup archive"
        rm -rf "$restore_tmp"
        exit 2
    fi

    # Show what would be restored
    echo "=== Files in backup ==="
    find "$restore_tmp" -type f | sed "s|${restore_tmp}/||" | sort
    echo ""
    echo "WARNING: Restoring will overwrite existing files."
    echo "The backup has been extracted to: ${restore_tmp}"
    echo "To apply, run: cp -a \"${restore_tmp}/.\" /"
    echo "Then restart affected services: systemctl restart nginx postfix dovecot fail2ban"
    echo ""
    echo "IMPORTANT: After applying, remove the temp directory (contains sensitive files):"
    echo "  rm -rf \"${restore_tmp}\""

    marvin_log "INFO" "Backup extracted to ${restore_tmp} — manual application required for safety"
    marvin_log "WARN" "Restore temp dir ${restore_tmp} contains sensitive files — clean up after applying"
    exit 0
fi

# ─── Backup mode ─────────────────────────────────────────────────────────────
marvin_log_json "INFO" "backup" "Backup starting"

mkdir -p "$DAILY_DIR" "$WEEKLY_DIR"
chmod 700 "$BACKUP_BASE" "$DAILY_DIR" "$WEEKLY_DIR"

# Build the list of files to back up (skip missing files silently)
BACKUP_FILES=()

_add_if_exists() {
    local path="$1"
    if [[ -e "$path" ]]; then
        BACKUP_FILES+=("$path")
    fi
}

# System configs
_add_if_exists /etc/nginx/nginx.conf
_add_if_exists /etc/nginx/sites-available/marvin
_add_if_exists /etc/nginx/conf.d/marvin-export-map.conf
_add_if_exists /etc/ssh/sshd_config
_add_if_exists /etc/fail2ban/jail.local
_add_if_exists /etc/cron.d/marvin
_add_if_exists /etc/hostname
_add_if_exists /etc/postfix/main.cf
_add_if_exists /etc/postfix/master.cf
_add_if_exists /etc/dovecot/dovecot.conf
_add_if_exists /etc/opendkim.conf
_add_if_exists /etc/rspamd/local.d
_add_if_exists /etc/ufw/user.rules
_add_if_exists /etc/ufw/user6.rules

# Fail2ban jail configs (directory)
if [[ -d /etc/fail2ban/jail.d ]]; then
    while IFS= read -r f; do
        BACKUP_FILES+=("$f")
    done < <(find /etc/fail2ban/jail.d -type f 2>/dev/null)
fi

# Application data — critical, non-regeneratable
_add_if_exists /home/marvin/blog/marvin-blog.db
_add_if_exists "${MARVIN_DIR}/data/comms/identity.json"
_add_if_exists "${MARVIN_DIR}/data/comms/peers.json"
_add_if_exists "${MARVIN_DIR}/data/comms/gpg-info.json"
_add_if_exists "${MARVIN_DIR}/data/comms/marvin-gpg-public.asc"
_add_if_exists /home/marvin/.gnupg/pubring.kbx
_add_if_exists /home/marvin/.gnupg/trustdb.gpg
# GPG private keys — required to restore signing capability
if [[ -d /home/marvin/.gnupg/private-keys-v1.d ]]; then
    while IFS= read -r f; do
        BACKUP_FILES+=("$f")
    done < <(find /home/marvin/.gnupg/private-keys-v1.d -type f 2>/dev/null)
fi

# Marvin config
_add_if_exists "${MARVIN_DIR}/.env"
_add_if_exists "${MARVIN_DIR}/config/webhook.conf"
_add_if_exists /etc/nginx/export-api-key.conf

# Lessons learned (curated knowledge, not auto-regenerated)
_add_if_exists "${MARVIN_DIR}/data/lessons-learned.json"

if [[ ${#BACKUP_FILES[@]} -eq 0 ]]; then
    marvin_log "ERROR" "No files found to back up"
    exit 1
fi

# Log what we're backing up
marvin_log "INFO" "Backing up ${#BACKUP_FILES[@]} files/dirs"

if marvin_is_dry_run; then
    marvin_log "INFO" "[DRY-RUN] Would back up ${#BACKUP_FILES[@]} items:"
    for f in "${BACKUP_FILES[@]}"; do
        marvin_log "INFO" "[DRY-RUN]   ${f}"
    done
    exit 0
fi

# Create the backup archive (include epoch to prevent same-day overwrites on re-runs)
BACKUP_FILE="${DAILY_DIR}/marvin-backup-${TODAY}-$(date +%s).tar.gz"

# Use tar with absolute paths, stripping the leading /
if tar -czf "${BACKUP_FILE}" --warning=no-file-changed "${BACKUP_FILES[@]}" 2>&1; then
    backup_size=$(du -sh "$BACKUP_FILE" | cut -f1)
    marvin_log "INFO" "Daily backup created: ${BACKUP_FILE} (${backup_size})"
else
    # tar may return non-zero if files changed during backup (WAL files)
    # Check if the archive was actually created
    if [[ -f "$BACKUP_FILE" && -s "$BACKUP_FILE" ]]; then
        backup_size=$(du -sh "$BACKUP_FILE" | cut -f1)
        marvin_log "WARN" "Backup created with warnings: ${BACKUP_FILE} (${backup_size})"
    else
        marvin_log "ERROR" "Backup failed — no archive created"
        exit 1
    fi
fi

# Verify the archive is valid
if ! tar -tzf "$BACKUP_FILE" >/dev/null 2>&1; then
    marvin_log "ERROR" "Backup archive is corrupt — removing"
    rm -f "$BACKUP_FILE"
    exit 1
fi

file_count=$(tar -tzf "$BACKUP_FILE" 2>/dev/null | wc -l)
marvin_log "INFO" "Backup verified: ${file_count} entries"

# ─── Weekly backup (copy Sunday's daily backup) ─────────────────────────────
day_of_week=$(date -u +%u)  # 7 = Sunday
if [[ "$day_of_week" -eq 7 ]]; then
    weekly_file="${WEEKLY_DIR}/marvin-weekly-${TODAY}.tar.gz"
    cp "$BACKUP_FILE" "$weekly_file"
    marvin_log "INFO" "Weekly backup created: ${weekly_file}"
fi

# ─── Retention: prune old backups ────────────────────────────────────────────
# Daily: keep last N
_prune_old() {
    local dir="$1" keep="$2"
    local count
    count=$(find "${dir}" -maxdepth 1 -name "*.tar.gz" 2>/dev/null | wc -l)
    if [[ "$count" -gt "$keep" ]]; then
        local to_delete=$((count - keep))
        find "${dir}" -maxdepth 1 -name "*.tar.gz" -printf '%T@ %p\n' 2>/dev/null \
            | sort -n | head -n "$to_delete" | cut -d' ' -f2- | while IFS= read -r old; do
            rm -f "$old"
            marvin_log "INFO" "Pruned old backup: ${old}"
        done
    fi
}

_prune_old "$DAILY_DIR" "$DAILY_RETENTION"
_prune_old "$WEEKLY_DIR" "$WEEKLY_RETENTION"

# ─── Write backup status for dashboard ───────────────────────────────────────
latest_daily=$(find "${DAILY_DIR}" -maxdepth 1 -name "*.tar.gz" -printf '%T@ %p\n' 2>/dev/null | sort -rn | head -1 | cut -d' ' -f2- || echo "")
latest_weekly=$(find "${WEEKLY_DIR}" -maxdepth 1 -name "*.tar.gz" -printf '%T@ %p\n' 2>/dev/null | sort -rn | head -1 | cut -d' ' -f2- || echo "")
daily_count=$(find "${DAILY_DIR}" -maxdepth 1 -name "*.tar.gz" 2>/dev/null | wc -l)
weekly_count=$(find "${WEEKLY_DIR}" -maxdepth 1 -name "*.tar.gz" 2>/dev/null | wc -l)

jq -n \
    --arg ts "$NOW" \
    --arg latest_daily "$(basename "${latest_daily:-none}")" \
    --arg latest_daily_size "$(du -sh "${latest_daily:-/dev/null}" 2>/dev/null | cut -f1 || echo "0")" \
    --argjson daily_count "$daily_count" \
    --argjson weekly_count "$weekly_count" \
    --argjson file_count "$file_count" \
    --arg latest_weekly "$(basename "${latest_weekly:-none}")" \
    '{
        timestamp: $ts,
        status: "ok",
        latest_daily: $latest_daily,
        latest_daily_size: $latest_daily_size,
        daily_count: $daily_count,
        weekly_count: $weekly_count,
        files_backed_up: $file_count,
        latest_weekly: $latest_weekly,
        retention: {daily: 7, weekly: 4}
    }' > "${DATA_DIR}/backup-status.json" 2>/dev/null || true

marvin_log_json "INFO" "backup" "Backup complete" \
    "$(jq -nc --argjson n "$file_count" --arg s "${backup_size:-unknown}" '{files: $n, size: $s}')"
