#!/usr/bin/env bash
# =============================================================================
# Marvin — Morning Check (runs daily at 06:00 UTC)
# =============================================================================
# Full system maintenance via Claude Code:
#   - Security audit
#   - Package updates
#   - Log cleanup
#   - Disk maintenance
#   - Service health review
# =============================================================================

set -euo pipefail
source "$(dirname "$0")/common.sh"

marvin_log "INFO" "=== MORNING CHECK STARTING ==="

check_claude || exit 1

# Read the morning prompt
MORNING_PROMPT=$(cat "${PROMPTS_DIR}/morning.md")

# Gather extra context for Claude
EXTRA_CONTEXT=$(cat << 'CONTEXT'
## Additional System Context

### Recent SSH Activity
```
CONTEXT
)
EXTRA_CONTEXT+=$(journalctl -u sshd --since "yesterday" --no-pager 2>/dev/null | tail -50 || echo "no journal data")
EXTRA_CONTEXT+=$(cat << 'CONTEXT'
```

### Disk Usage
```
CONTEXT
)
EXTRA_CONTEXT+=$(df -h 2>/dev/null || echo "df not available")
EXTRA_CONTEXT+=$(cat << 'CONTEXT'
```

### Failed Services
```
CONTEXT
)
EXTRA_CONTEXT+=$(systemctl --failed --no-pager 2>/dev/null || echo "systemctl not available")
EXTRA_CONTEXT+=$(cat << 'CONTEXT'
```

### Top Processes by Memory
```
CONTEXT
)
EXTRA_CONTEXT+=$(ps aux --sort=-%mem | head -15 2>/dev/null || echo "ps not available")
EXTRA_CONTEXT+=$(cat << 'CONTEXT'
```

### Fail2ban Status
```
CONTEXT
)
EXTRA_CONTEXT+=$(fail2ban-client status sshd 2>/dev/null || echo "fail2ban not available")
EXTRA_CONTEXT+=$(cat << 'CONTEXT'
```

### Pending Updates
```
CONTEXT
)
EXTRA_CONTEXT+=$(apt list --upgradable 2>/dev/null | head -20 || echo "apt not available")
EXTRA_CONTEXT+="
\`\`\`"

FULL_PROMPT="${MORNING_PROMPT}

${EXTRA_CONTEXT}"

# Run Claude with the morning prompt
# Using --allowedTools to give it system access
OUTPUT=$(run_claude "morning-check" "$FULL_PROMPT")

# Save the morning report
cat > "${BLOG_DIR}/${TODAY}-morning.md" << EOF
# Morning Report — ${TODAY}

${OUTPUT}

---
*Generated by Marvin at ${NOW}*
EOF

marvin_log "INFO" "=== MORNING CHECK COMPLETE ==="
