#!/usr/bin/env bash
# =============================================================================
# Marvin — Morning Check (runs daily at 06:00 UTC)
# =============================================================================
# Full system maintenance via Claude Code:
#   - Pull latest code from GitHub (new prompts, instructions, projects)
#   - Process and learn from incoming changes
#   - Security audit
#   - Package updates
#   - Log cleanup
#   - Disk maintenance
#   - Service health review
# =============================================================================

set -euo pipefail
source "$(dirname "$0")/common.sh"

marvin_log "INFO" "=== MORNING CHECK STARTING ==="

# ─────────────────────────────────────────────────────────────────────────────
# Phase 0: Pull latest code from GitHub
# ─────────────────────────────────────────────────────────────────────────────
# Humans (Pavel) or Marvin himself may have pushed new prompts, code, or
# project ideas to the repo. Pull them in before doing anything else.

PULL_SUMMARY=""
INCOMING_DIFF=""
INCOMING_LOG=""
INCOMING_FULL_DIFF=""

if [[ -f "$(dirname "$0")/lib/github.sh" ]]; then
    source "$(dirname "$0")/lib/github.sh"

    if github_check_token 2>/dev/null; then
        marvin_log "INFO" "Pulling latest code from GitHub..."
        cd "$MARVIN_DIR"
        github_setup_remote

        # Stash any local changes so they don't block the pull
        # (fix-issues.sh and self-enhance may leave uncommitted edits)
        local_dirty=false
        stash_created=false
        if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null; then
            local_dirty=true
            marvin_log "INFO" "Stashing local changes before pull..."
            if git stash push -m "morning-check-auto-stash-${TODAY}" --quiet 2>/dev/null; then
                stash_created=true
            else
                marvin_log "WARN" "Could not stash local changes — pull may fail"
            fi
        fi

        # Record the current HEAD before pulling
        OLD_HEAD=$(git rev-parse HEAD 2>/dev/null || echo "unknown")

        # Fetch first so we know if there's anything to pull
        git fetch --prune origin 2>/dev/null || true

        # Pull with rebase to keep history clean
        pull_output=$(git pull --rebase origin main 2>&1) && pull_ok=true || pull_ok=false
        marvin_log "INFO" "git pull output: ${pull_output}"
        if [[ "$pull_ok" == "true" ]]; then
            NEW_HEAD=$(git rev-parse HEAD 2>/dev/null || echo "unknown")

            if [[ "$OLD_HEAD" != "$NEW_HEAD" ]]; then
                # There are new commits — capture what changed
                INCOMING_DIFF=$(git diff --stat "$OLD_HEAD".."$NEW_HEAD" 2>/dev/null || echo "")
                INCOMING_LOG=$(git log --oneline "$OLD_HEAD".."$NEW_HEAD" 2>/dev/null || echo "")
                INCOMING_FULL_DIFF=$(git diff "$OLD_HEAD".."$NEW_HEAD" 2>/dev/null | head -2000 || echo "")

                COMMIT_COUNT=$(echo "$INCOMING_LOG" | wc -l | tr -d ' ')
                PULL_SUMMARY="Pulled ${COMMIT_COUNT} new commit(s) from GitHub."

                marvin_log "INFO" "$PULL_SUMMARY"
                marvin_log "INFO" "Changed files:\n${INCOMING_DIFF}"

                # Make new scripts executable
                chmod +x "${MARVIN_DIR}/agent/"*.sh 2>/dev/null || true
                chmod +x "${MARVIN_DIR}/setup/"*.sh 2>/dev/null || true
            else
                PULL_SUMMARY="Already up to date — no new commits."
                marvin_log "INFO" "$PULL_SUMMARY"
            fi
        else
            PULL_SUMMARY="Git pull failed — will work with current code."
            marvin_log "WARN" "Git pull --rebase failed, attempting merge..."
            git rebase --abort 2>/dev/null || true
            git pull origin main 2>&1 || {
                marvin_log "ERROR" "Git pull failed entirely"
            }
        fi

        # Restore stashed local changes (only if stash was actually created)
        if [[ "$stash_created" == "true" ]]; then
            marvin_log "INFO" "Restoring stashed local changes..."
            _safe_stash_pop
        elif [[ "$local_dirty" == "true" ]]; then
            marvin_log "WARN" "Working tree was dirty but stash failed — local changes may conflict with pulled code"
        fi

        # Data files will be regenerated by the next health-monitor/update-website run

        # ── Stale branch cleanup ──────────────────────────────────────────────
        # PRs merged on GitHub leave local branches behind. Clean up branches
        # whose remote counterpart was deleted (i.e., PR was merged/closed).
        marvin_log "INFO" "Cleaning stale local branches..."
        stale_cleaned=0
        while IFS= read -r branch; do
            [[ -z "$branch" || "$branch" == "main" ]] && continue
            # Keep branches that still have a remote counterpart (local check after fetch --prune)
            if git show-ref --verify --quiet "refs/remotes/origin/${branch}" 2>/dev/null; then
                continue
            fi
            # Only delete if merged into main (safe) or older than 7 days
            if git branch --merged main 2>/dev/null | grep -qF "  ${branch}"; then
                git branch -d "$branch" 2>/dev/null && {
                    stale_cleaned=$((stale_cleaned + 1))
                    marvin_log "INFO" "Deleted merged stale branch ${branch}"
                } || true
            else
                # Check branch age — force-delete if >7 days old with no remote
                branch_date=$(git log -1 --format='%ci' "$branch" 2>/dev/null | cut -d' ' -f1)
                if [[ -n "$branch_date" ]]; then
                    branch_epoch=$(date -d "$branch_date" +%s 2>/dev/null) || continue
                    now_epoch=$(date +%s)
                    age_days=$(( (now_epoch - branch_epoch) / 86400 ))
                    if [[ "$age_days" -gt 7 ]]; then
                        git branch -D "$branch" 2>/dev/null && stale_cleaned=$((stale_cleaned + 1)) || true
                        marvin_log "INFO" "Force-deleted stale branch ${branch} (${age_days} days old, no remote)"
                    fi
                fi
            fi
        done < <(git branch 2>/dev/null | grep -v '^\* ' | sed 's/^ *//')
        if [[ "$stale_cleaned" -gt 0 ]]; then
            marvin_log "INFO" "Cleaned ${stale_cleaned} stale local branch(es)"
        fi
    else
        PULL_SUMMARY="No GitHub token — working with local code only."
        marvin_log "INFO" "$PULL_SUMMARY"
    fi
else
    PULL_SUMMARY="GitHub library not available — working with local code only."
    marvin_log "INFO" "$PULL_SUMMARY"
fi

# ─────────────────────────────────────────────────────────────────────────────
# Phase 0b: Process incoming changes with Claude
# ─────────────────────────────────────────────────────────────────────────────
# If new code/prompts arrived, Marvin should read, understand, and act on them.

if [[ -n "$INCOMING_DIFF" ]]; then
    marvin_log "INFO" "Processing incoming changes from GitHub..."

    SYNC_PROMPT=$(cat "${PROMPTS_DIR}/sync-learn.md" 2>/dev/null || echo "")

    if [[ -n "$SYNC_PROMPT" ]]; then
        SYNC_CONTEXT="## Incoming Changes Summary

### Git Pull Status
${PULL_SUMMARY}

### Commits
\`\`\`
${INCOMING_LOG:0:5000}
\`\`\`

### Changed Files
\`\`\`
${INCOMING_DIFF}
\`\`\`

### Full Diff (truncated to 2000 chars)
\`\`\`diff
${INCOMING_FULL_DIFF}
\`\`\`

### Current Enhancement Roadmap
$(cat "${MARVIN_DIR}/POSSIBLE_ENHANCEMENTS.md" 2>/dev/null | head -100 || echo "Not found")

### Current Codebase Structure
\`\`\`
$(find "${MARVIN_DIR}/agent" -type f -name "*.sh" | sort)
$(find "${MARVIN_DIR}/agent/prompts" -type f -name "*.md" | sort)
$(find "${MARVIN_DIR}/web" -type f -not -path "*/node_modules/*" -not -path "*/.next/*" | sort | head -50)
\`\`\`"

        SYNC_FULL="${SYNC_PROMPT}

${SYNC_CONTEXT}"

        SYNC_OUTPUT=$(run_claude "sync-and-learn" "$SYNC_FULL")

        # Save the learning report
        LEARN_FILE="${DATA_DIR}/enhancements/${TODAY}-sync-learn-${TIMESTAMP}.md"
        cat > "$LEARN_FILE" << EOF
# Sync & Learn Report — ${NOW}

## Pull Summary
${PULL_SUMMARY}

## Claude's Analysis & Actions

${SYNC_OUTPUT}

---
*Triggered by git pull at morning check*
EOF

        marvin_log "INFO" "Sync-and-learn report saved: ${LEARN_FILE}"
    else
        marvin_log "WARN" "sync-learn.md prompt not found — skipping change analysis"
    fi
fi

check_claude || exit 1

# Read the morning prompt
MORNING_PROMPT=$(cat "${PROMPTS_DIR}/morning.md")

# Gather extra context for Claude
EXTRA_CONTEXT=$(cat << 'CONTEXT'
## Additional System Context

### Recent SSH Activity
```
CONTEXT
)
EXTRA_CONTEXT+=$(journalctl -u sshd --since "yesterday" --no-pager 2>/dev/null | tail -50 || echo "no journal data")
EXTRA_CONTEXT+=$(cat << 'CONTEXT'
```

### Disk Usage
```
CONTEXT
)
EXTRA_CONTEXT+=$(df -h 2>/dev/null | head -20 || echo "df not available")
EXTRA_CONTEXT+=$(cat << 'CONTEXT'
```

### Failed Services
```
CONTEXT
)
EXTRA_CONTEXT+=$(systemctl --failed --no-pager 2>/dev/null | head -30 || echo "systemctl not available")
EXTRA_CONTEXT+=$(cat << 'CONTEXT'
```

### Top Processes by Memory
```
CONTEXT
)
EXTRA_CONTEXT+=$(ps aux --sort=-%mem | head -15 2>/dev/null || echo "ps not available")
EXTRA_CONTEXT+=$(cat << 'CONTEXT'
```

### Fail2ban Status
```
CONTEXT
)
EXTRA_CONTEXT+=$(fail2ban-client status sshd 2>/dev/null || echo "fail2ban not available")
EXTRA_CONTEXT+=$(cat << 'CONTEXT'
```

### Pending Updates
```
CONTEXT
)
EXTRA_CONTEXT+=$(apt list --upgradable 2>/dev/null | head -20 || echo "apt not available")
EXTRA_CONTEXT+="
\`\`\`"

# Add pull summary to context for Claude's morning check
if [[ -n "${PULL_SUMMARY:-}" ]]; then
    EXTRA_CONTEXT+="

### GitHub Pull Status
${PULL_SUMMARY}"
    if [[ -n "${INCOMING_DIFF:-}" ]]; then
        EXTRA_CONTEXT+="

### Files Changed from GitHub
\`\`\`
${INCOMING_DIFF}
\`\`\`"
    fi
fi

FULL_PROMPT="${MORNING_PROMPT}

${EXTRA_CONTEXT}"

# Run Claude with the morning prompt
# Using --allowedTools to give it system access
OUTPUT=$(run_claude "morning-check" "$FULL_PROMPT")

# Save the morning report — check if Claude already wrote the file directly
MORNING_FILE="${BLOG_DIR}/${TODAY}-morning.md"
if [[ -f "$MORNING_FILE" ]] && head -1 "$MORNING_FILE" | grep -q '^# '; then
    marvin_log "INFO" "Claude created morning report directly — preserving that"
else
    cat > "$MORNING_FILE" << EOF
# Morning Report — ${TODAY}

${OUTPUT}

---
*Generated by Marvin at ${NOW}*
EOF
fi

# Insert into SQLite blog database (dual write: markdown + SQLite)
INSERT_SCRIPT="${WEB_DIR}/scripts/insert-blog.sh"
if [[ -x "$INSERT_SCRIPT" ]]; then
    marvin_log "INFO" "Inserting morning blog into SQLite..."
    "$INSERT_SCRIPT" --date "$TODAY" --type morning --file "$MORNING_FILE" --bilingual 2>&1 || \
        marvin_log "WARN" "SQLite insert failed for morning blog (non-fatal)"
else
    marvin_log "INFO" "insert-blog.sh not found — skipping SQLite insert"
fi

marvin_log "INFO" "=== MORNING CHECK COMPLETE ==="
